version: '3'

services:
  web:
    build: .
    command:
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py createsuperuser --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
    volumes:
      - .:/spa
    ports:
      - "8000:8000"
