version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'spa-db'
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/spa
    ports:
      - "8000:8000"
    depends_on:
      - db
