# Generated by Django 3.2.5 on 2022-05-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Portal name!', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New product!', max_length=50)),
                ('minimal_requirements', models.CharField(default='min req details!', max_length=50)),
                ('source_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='music title!', max_length=50)),
                ('url', models.URLField(default='www.google.com')),
                ('used_in_trailer', models.BooleanField(default=False)),
                ('music_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dop.musicportal')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dop.product')),
            ],
        ),
    ]
