# Generated by Django 3.2.5 on 2022-05-25 16:41

from django.db import migrations

def create_defaults(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Product = apps.get_model('dop', 'Product')
    Music = apps.get_model('dop', 'Music')
    MusicPortal = apps.get_model('dop', 'MusicPortal')

    p = Product.objects.create(title = "New product!", minimal_requirements = "FCPX DVR", source_size = 256000)
    mp = MusicPortal.objects.create(name = "google.com")


    Music.objects.create(
        title = "Trailer music",
        url = "www.google.com",
        used_in_trailer = True,
        music_portal = mp,
        product = p
    )

    Music.objects.create(
        title = "Tutorial music",
        url = "www.google.com",
        used_in_trailer = True,
        music_portal = mp,
        product = p
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_defaults),
    ]
